### ISSUE TITLE
Failing when there aren't any card's number

### ISSUE THREAD

**Issue by denysdovhan** [beshkenadze/typographic-bank-card#3]
I'm trying to process plain text through this package as pard of typographer. If I process text without any card's number, get an error:

**Usage:**

```
bar(foo(cards("Phone number: +180951100392")))
```

**Output:**

```
.../node_modules/typographic-bank-card/index.js:28
        for (var i = 0; i < cards.length; i++) {
                                 ^

TypeError: Cannot read property 'length' of null
    at formatCards (.../node_modules/typographic-bank-card/index.js:28:34)
    at module.exports (.../node_modules/typographic-bank-card/index.js:36:12)
    at Object.<anonymous> (.../foo.js:6:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by iamstarkov** [comment]
@beshkenadze @denysdovhan can anybody add tests for this case?

**Comment by beshkenadze** [comment]
@iamstarkov At the bottom of the file https://github.com/beshkenadze/typographic-bank-card/blob/master/test/test.js

**Comment by iamstarkov** [comment]
great

**Comment by denysdovhan** [comment]
:+1:
